#!/usr/bin/env bash
# set -x


OUT_DIR="download"

mkdir -p $OUT_DIR

download() {
        out="$OUT_DIR/${1:5}"

        if [ -f "$out" ]; then
                echo "[INFO]: $out already exists!"
                return 0
        fi

        curl -s "https://upload.wikimedia.org/wikipedia/commons/$1" > "$out"
        sleep 1s

        return $?
}

files=(
 "9/9d/Hwatu_January_Hikari.svg"
 "d/da/Hwatu_January_Tanzaku.svg"
 "e/e1/Hwatu_January_Kasu_1.svg"
 "f/fe/Hwatu_January_Kasu_2.svg"
 "0/03/Hwatu_February_Tane.svg"
 "b/bd/Hwatu_February_Tanzaku.svg"
 "e/e4/Hwatu_February_Kasu_1.svg"
 "3/31/Hwatu_February_Kasu_2.svg"
 "9/93/Hwatu_March_Hikari.svg"
 "f/f3/Hwatu_March_Tanzaku.svg"
 "b/b1/Hwatu_March_Kasu_1.svg"
 "1/12/Hwatu_March_Kasu_2.svg"
 "e/e6/Hwatu_April_Tane.svg"
 "7/75/Hwatu_April_Tanzaku.svg"
 "0/00/Hwatu_April_Kasu_1.svg"
 "7/7c/Hwatu_April_Kasu_2.svg"
 "0/0f/Hwatu_May_Tanzaku.svg"
 "0/0e/Hwatu_May_Kasu_1.svg"
 "4/4b/Hwatu_May_Kasu_2.svg"
 "7/7e/Hwatu_May_Tane.svg"
 "e/e1/Hwatu_June_Tane.svg"
 "f/fc/Hwatu_June_Tanzaku.svg"
 "2/22/Hwatu_June_Kasu_1.svg"
 "9/93/Hwatu_June_Kasu_2.svg"
 "d/d5/Hwatu_July_Tane.svg"
 "3/31/Hwatu_July_Tanzaku.svg"
 "d/d9/Hwatu_July_Kasu_1.svg"
 "d/d4/Hwatu_July_Kasu_2.svg"
 "c/c6/Hwatu_August_Hikari.svg"
 "c/c7/Hwatu_August_Tane.svg"
 "f/f4/Hwatu_August_Kasu_1.svg"
 "6/68/Hwatu_August_Kasu_2.svg"
 "4/4c/Hwatu_September_Tanzaku.svg"
 "a/a9/Hwatu_September_Kasu_1.svg"
 "d/dd/Hwatu_September_Kasu_2.svg"
 "c/c5/Hwatu_September_Tane.svg"
 "f/f0/Hwatu_October_Tane.svg"
 "c/c0/Hwatu_October_Tanzaku.svg"
 "0/08/Hwatu_October_Kasu_1.svg"
 "5/59/Hwatu_October_Kasu_2.svg"
 "d/d1/Hwatu_November_Hikari.svg"
 "e/e6/Hwatu_November_Kasu_1.svg"
 "8/89/Hwatu_November_Kasu_3.svg"
 "0/0f/Hwatu_November_Kasu_2.svg"
 "6/6b/Hwatu_December_Hikari.svg"
 "1/17/Hwatu_December_Tane.svg"
 "1/19/Hwatu_December_Tanzaku.svg"
 "6/61/Hwatu_December_Kasu.svg")

j=47
for i in $(seq 0 47);
do
        eval printf -v bar "*%.0s" {1..$i}
        eval printf -v gap "x%.0s" {1..$j}
        gap="${gap//x/ }"
        printf -v display '[%s%s]' "$bar" "$gap"

        download "${files[i]}"

        echo -ne "$display\r"
        j=$((j-1))
        sleep 0.25s
done

echo ""
